/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes.web/__root'
import { Route as DesignSystemRouteImport } from './routes.web/design-system'
import { Route as BlogIndexRouteImport } from './routes.web/blog.index'
import { Route as BlogSlugRouteImport } from './routes.web/blog.$slug'
import { Route as TalksIndexRouteImport } from './routes.web/talks.index'
import { Route as TalksSlugRouteImport } from './routes.web/talks.$slug'
import { Route as Char123LangChar125IndexRouteImport } from './routes.web/{-$lang}.index'
import { Route as Char123LangChar125ContactRouteImport } from './routes.web/{-$lang}.contact'
import { Route as Char123LangChar125CvRouteImport } from './routes.web/{-$lang}.cv'
import { Route as Char123LangChar125ResumeRouteImport } from './routes.web/{-$lang}.resume'
import { Route as Char123LangChar125ResumeSlugRouteImport } from './routes.web/{-$lang}.resume_.$slug'
import { Route as Char123LangChar125ResumeGroupGroupRouteImport } from './routes.web/{-$lang}.resume_.group.$group'

const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksIndexRoute = TalksIndexRouteImport.update({
  id: '/talks/',
  path: '/talks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksSlugRoute = TalksSlugRouteImport.update({
  id: '/talks/$slug',
  path: '/talks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/{-$lang}/',
  path: '/{-$lang}/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125ContactRoute =
  Char123LangChar125ContactRouteImport.update({
    id: '/{-$lang}/contact',
    path: '/{-$lang}/contact',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125CvRoute = Char123LangChar125CvRouteImport.update({
  id: '/{-$lang}/cv',
  path: '/{-$lang}/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125ResumeRoute =
  Char123LangChar125ResumeRouteImport.update({
    id: '/{-$lang}/resume',
    path: '/{-$lang}/resume',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125ResumeSlugRoute =
  Char123LangChar125ResumeSlugRouteImport.update({
    id: '/{-$lang}/resume_/$slug',
    path: '/{-$lang}/resume/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125ResumeGroupGroupRoute =
  Char123LangChar125ResumeGroupGroupRouteImport.update({
    id: '/{-$lang}/resume_/group/$group',
    path: '/{-$lang}/resume/group/$group',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/design-system': typeof DesignSystemRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/cv': typeof Char123LangChar125CvRoute
  '/{-$lang}/resume': typeof Char123LangChar125ResumeRoute
  '/blog/': typeof BlogIndexRoute
  '/talks/': typeof TalksIndexRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/resume/$slug': typeof Char123LangChar125ResumeSlugRoute
  '/{-$lang}/resume/group/$group': typeof Char123LangChar125ResumeGroupGroupRoute
}
export interface FileRoutesByTo {
  '/design-system': typeof DesignSystemRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/cv': typeof Char123LangChar125CvRoute
  '/{-$lang}/resume': typeof Char123LangChar125ResumeRoute
  '/blog': typeof BlogIndexRoute
  '/talks': typeof TalksIndexRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/{-$lang}/resume/$slug': typeof Char123LangChar125ResumeSlugRoute
  '/{-$lang}/resume/group/$group': typeof Char123LangChar125ResumeGroupGroupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/design-system': typeof DesignSystemRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/cv': typeof Char123LangChar125CvRoute
  '/{-$lang}/resume': typeof Char123LangChar125ResumeRoute
  '/blog/': typeof BlogIndexRoute
  '/talks/': typeof TalksIndexRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/resume_/$slug': typeof Char123LangChar125ResumeSlugRoute
  '/{-$lang}/resume_/group/$group': typeof Char123LangChar125ResumeGroupGroupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/design-system'
    | '/blog/$slug'
    | '/talks/$slug'
    | '/{-$lang}/contact'
    | '/{-$lang}/cv'
    | '/{-$lang}/resume'
    | '/blog/'
    | '/talks/'
    | '/{-$lang}/'
    | '/{-$lang}/resume/$slug'
    | '/{-$lang}/resume/group/$group'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/design-system'
    | '/blog/$slug'
    | '/talks/$slug'
    | '/{-$lang}/contact'
    | '/{-$lang}/cv'
    | '/{-$lang}/resume'
    | '/blog'
    | '/talks'
    | '/{-$lang}'
    | '/{-$lang}/resume/$slug'
    | '/{-$lang}/resume/group/$group'
  id:
    | '__root__'
    | '/design-system'
    | '/blog/$slug'
    | '/talks/$slug'
    | '/{-$lang}/contact'
    | '/{-$lang}/cv'
    | '/{-$lang}/resume'
    | '/blog/'
    | '/talks/'
    | '/{-$lang}/'
    | '/{-$lang}/resume_/$slug'
    | '/{-$lang}/resume_/group/$group'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DesignSystemRoute: typeof DesignSystemRoute
  BlogSlugRoute: typeof BlogSlugRoute
  TalksSlugRoute: typeof TalksSlugRoute
  Char123LangChar125ContactRoute: typeof Char123LangChar125ContactRoute
  Char123LangChar125CvRoute: typeof Char123LangChar125CvRoute
  Char123LangChar125ResumeRoute: typeof Char123LangChar125ResumeRoute
  BlogIndexRoute: typeof BlogIndexRoute
  TalksIndexRoute: typeof TalksIndexRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  Char123LangChar125ResumeSlugRoute: typeof Char123LangChar125ResumeSlugRoute
  Char123LangChar125ResumeGroupGroupRoute: typeof Char123LangChar125ResumeGroupGroupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks/': {
      id: '/talks/'
      path: '/talks'
      fullPath: '/talks/'
      preLoaderRoute: typeof TalksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks/$slug': {
      id: '/talks/$slug'
      path: '/talks/$slug'
      fullPath: '/talks/$slug'
      preLoaderRoute: typeof TalksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/{-$lang}'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/contact': {
      id: '/{-$lang}/contact'
      path: '/{-$lang}/contact'
      fullPath: '/{-$lang}/contact'
      preLoaderRoute: typeof Char123LangChar125ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/cv': {
      id: '/{-$lang}/cv'
      path: '/{-$lang}/cv'
      fullPath: '/{-$lang}/cv'
      preLoaderRoute: typeof Char123LangChar125CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/resume': {
      id: '/{-$lang}/resume'
      path: '/{-$lang}/resume'
      fullPath: '/{-$lang}/resume'
      preLoaderRoute: typeof Char123LangChar125ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/resume_/$slug': {
      id: '/{-$lang}/resume_/$slug'
      path: '/{-$lang}/resume/$slug'
      fullPath: '/{-$lang}/resume/$slug'
      preLoaderRoute: typeof Char123LangChar125ResumeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/resume_/group/$group': {
      id: '/{-$lang}/resume_/group/$group'
      path: '/{-$lang}/resume/group/$group'
      fullPath: '/{-$lang}/resume/group/$group'
      preLoaderRoute: typeof Char123LangChar125ResumeGroupGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DesignSystemRoute: DesignSystemRoute,
  BlogSlugRoute: BlogSlugRoute,
  TalksSlugRoute: TalksSlugRoute,
  Char123LangChar125ContactRoute: Char123LangChar125ContactRoute,
  Char123LangChar125CvRoute: Char123LangChar125CvRoute,
  Char123LangChar125ResumeRoute: Char123LangChar125ResumeRoute,
  BlogIndexRoute: BlogIndexRoute,
  TalksIndexRoute: TalksIndexRoute,
  Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
  Char123LangChar125ResumeSlugRoute: Char123LangChar125ResumeSlugRoute,
  Char123LangChar125ResumeGroupGroupRoute:
    Char123LangChar125ResumeGroupGroupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
